@url=http://localhost:10000
@googleApiKey=AIzaSyAZoFB7dKKybaOY-BbBtbrCy-9uBPEy3-4
### @name CompanyInsert
PUT {{url}}/company
Content-Type: application/json

{
  "name": "Stolkhomsmassan",
  "geo": {
    "lat": 59.2760828,
    "long":18.0048304
  }
}

### @name CompanyUpdate
POST {{url}}/company/5cfa860d8c88743fb418c5e9
Content-Type: application/json

{
  "name": "Stolkhomsmassan2"
}

### @name CompanyDelete
DELETE {{url}}/people/clear
Content-Type: application/json


### @name googleApiZipCode
GET https://maps.googleapis.com/maps/api/geocode/json?address=21050455&key={{googleApiKey}}
